### ISSUE TITLE
Real-Time

### ISSUE THREAD

**Issue by AlexYiningLiu** [ishank-juneja/L1-optimal-paths-Stabilization#1]
Does this code work on real-time incoming frames? Thanks.

**Comment by ishank-juneja** [comment]
Hi Alex,
Unfortunately not yet. 
The method (L1 optimal camera paths) is an offline video stabilization method (which means it takes the entire video file at once and is not real time for a series of incoming frames)
My plan is to make this real time/streamable by slicing the video into sections and process a shorter series of frames fast enough that the time taken is equal to the time required for playing a video section of the same size.
This would ensure that there is only a constant delay between the unstable input and stabilized output.
Right now the code only slices the files and then joins them back together in an offline manner. I am yet to use the python threading library to the 2 things (playing frames and stabilizing next set of frames) in parallel.
I think I will do this in September when I have some more time. Will update here when done.

**Comment by RingoWRW** [comment]
Some questions about subspacestab:
First I run the program,it has some bug,but when I figure out the bug.I find the results of SVD's matrixes are zero matrix.
But I don't know why.When I debug only the first s is singular matrix.
So did you fininsh  the subspace code?And Could this code achieve a stable video? 
If you're be interested in the research area,Can I send an email for you to contact this topic. hhh  Thanks

**Comment by ishank-juneja** [comment]
Hi RingoWRW,
Thank you for your comment and for taking interest in this work.
You are correct, the subspace stabilization method has not been implemented completely yet.
In particular I believe the trajectory matrix warping part (end of code file) is left.
You have mentioned results of the SVD matrix are all zero. I am not sure why that is the case since this code file was written by my collaborator @ASKanse.
Please do send an email at ishankjuneja@gmail.com since I am currently (off-and-on) trying to make the sub space method work.

**Comment by ishank-juneja** [comment]
@AlexYiningLiu it turns out, it is not possible (or very difficult based on my attempts and rough processing time calculations) to make the method work in real time with regular real time. Closing issue

**Comment by ishank-juneja** [comment]
@RingoWRW please see my fork and pull request on an existing CPP repository for an implementation of subSpace stabilization (added few days from posting):
[https://github.com/ishank-juneja/SubspaceStab](https://github.com/ishank-juneja/SubspaceStab)

Closing Issue
