### ISSUE TITLE
online stabilization

### ISSUE THREAD

**Issue by hosea7456** [ishank-juneja/L1-optimal-paths-Stabilization#6]
Hi, thanks for your great jobs!
I wonder if this code can use in online stabilization for camera?

**Comment by ishank-juneja** [comment]
Hi @hosea7456  and thank you for your interest.

Unfortunately the code here requires an entire video file from the get-go and cannot work in an online manner.

Although the L1 optimal camera paths method is an offline method, we attempted to modify it to operate online and process one window at a time however we were not successful on that task.

Let me know if you have more questions and feel free to close this issue otherwise.

**Comment by hosea7456** [comment]
> Hi @hosea7456 and thank you for your interest.
> 
> Unfortunately the code here requires an entire video file from the get-go and cannot work in an online manner.
> 
> Although the L1 optimal camera paths method is an offline method, we attempted to modify it to operate online and process one window at a time however we were not successful on that task.
> 
> Let me know if you have more questions and feel free to close this issue otherwise.

I got it, thank you so much!
